/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant':            '#e2e2e7',
        'outline-variant':            '#cfc4c5',
        'tertiary-fixed-dim':         '#c6c6cb',
        'on-primary-fixed':           '#1b1b1b',
        'background':                 '#f9f9fe',
        'on-primary-container':       '#848484',
        'tertiary-container':         '#1a1b1f',
        'secondary':                  '#5d5f5f',
        'primary':                    '#000000',
        'on-background':              '#1a1c1f',
        'error':                      '#ba1a1a',
        'tertiary':                   '#000000',
        'surface-bright':             '#f9f9fe',
        'on-surface':                 '#1a1c1f',
        'on-tertiary':                '#ffffff',
        'inverse-surface':            '#2e3034',
        'surface-container-lowest':   '#ffffff',
        'secondary-fixed':            '#e2e2e2',
        'primary-fixed':              '#e2e2e2',
        'inverse-primary':            '#c6c6c6',
        'surface-container-low':      '#f3f3f8',
        'on-secondary-fixed':         '#1a1c1c',
        'surface-container':          '#ededf2',
        'primary-fixed-dim':          '#c6c6c6',
        'on-secondary':               '#ffffff',
        'on-error-container':         '#93000a',
        'on-primary':                 '#ffffff',
        'surface-container-high':     '#e8e8ed',
        'primary-container':          '#1b1b1b',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'secondary-container':        '#dfe0e0',
        'outline':                    '#7e7576',
        'on-tertiary-container':      '#838388',
        'surface-container-highest':  '#e2e2e7',
        'on-surface-variant':         '#4c4546',
        'surface':                    '#f9f9fe',
        'inverse-on-surface':         '#f0f0f5',
        'surface-dim':                '#d9dade',
        'on-secondary-container':     '#616363',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        lg:              '48px',
        xs:              '8px',
        base:            '4px',
        xl:              '80px',
        sm:              '16px',
        gutter:          '24px',
        'container-max': '1440px',
        md:              '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'label-caps':         ['JetBrains Mono', 'monospace'],
        'headline-xl':        ['Montserrat', 'sans-serif'],
        'display-lg':         ['Montserrat', 'sans-serif'],
        'body-lg':            ['Hanken Grotesk', 'sans-serif'],
        'body-md':            ['Hanken Grotesk', 'sans-serif'],
        'headline-lg':        ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '32px', fontWeight: '700' }],
        'label-caps':         ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-xl':        ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg':         ['80px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '900' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg':        ['32px', { lineHeight: '38px', fontWeight: '700' }],
      },
      keyframes: {
        'slide-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        'slide-up': 'slide-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
}

